#! /bin/sh

## AUTO START

sxhkd &
xfce4-panel &

##feh --bg-fill ~/Pictures/wallpapers/road2.jpg --bg-fill ~/Pictures/wallpapers/road3.jpg &
picom --no-fading-openclose &


## MONITORS

bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9

## RULES

# Drop Down apps

bspc rule -a Xfce4-terminal state=floating

# Regular rules

bspc rule -a 'TeamSpeak 3' desktop=^4

bspc rule -a Steam desktop=^6 follow=off focus=off state=floating

bspc rule -a discord desktop=^5 follow=off focus=off

bspc rule -a dota2 desktop=^3 focus=on

## BSPWM CONFIGURATION

bspc config border_width	1 

bspc config window_gap		0 

bspc config focused_border_color "#0A84FF"
bspc config normal_border_color "#000000"

bspc config pointer_motion_interval 7ms


#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true






